# Generated by Django 5.0.1 on 2026-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seismicdata',
            name='seismic_factor',
            field=models.FloatField(blank=True, help_text='Importance factor derived from zone', null=True),
        ),
    ]
