# Generated by Cursor on 2026-02-03

from django.db import migrations, models


TEMPERATURE_TABLE = "locations_temperaturedata"


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seismicdata_seismic_factor"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = '{TEMPERATURE_TABLE}'
          AND column_name = 'min_temp'
    ) THEN
        ALTER TABLE {TEMPERATURE_TABLE} RENAME COLUMN min_temp TO min_temp_c;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = '{TEMPERATURE_TABLE}'
          AND column_name = 'max_temp'
    ) THEN
        ALTER TABLE {TEMPERATURE_TABLE} RENAME COLUMN max_temp TO max_temp_c;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = '{TEMPERATURE_TABLE}'
          AND column_name = 'notes'
    ) THEN
        ALTER TABLE {TEMPERATURE_TABLE} ADD COLUMN notes text;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = '{TEMPERATURE_TABLE}'
          AND column_name = 'source_code'
    ) THEN
        ALTER TABLE {TEMPERATURE_TABLE}
            ADD COLUMN source_code varchar(50) NOT NULL DEFAULT 'ingestion';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = '{TEMPERATURE_TABLE}'
          AND column_name = 'source_station'
    ) THEN
        ALTER TABLE {TEMPERATURE_TABLE}
            ADD COLUMN source_station varchar(100) NOT NULL DEFAULT 'ingestion';
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="temperaturedata",
                    name="min_temp",
                    field=models.FloatField(db_column="min_temp_c"),
                ),
                migrations.AlterField(
                    model_name="temperaturedata",
                    name="max_temp",
                    field=models.FloatField(db_column="max_temp_c"),
                ),
                migrations.AddField(
                    model_name="temperaturedata",
                    name="notes",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="temperaturedata",
                    name="source_code",
                    field=models.CharField(default="ingestion", max_length=50),
                ),
                migrations.AddField(
                    model_name="temperaturedata",
                    name="source_station",
                    field=models.CharField(default="ingestion", max_length=100),
                ),
            ],
        ),
    ]
